In [2]:
import numpy as np
list_ = [ "1","2","3","4","5" ]
array_list = np.array(object = list_)

In [3]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.

In [8]:
print("type of list_" ,type(list))

type of list_ <class 'type'>


In [9]:
print("type of array list",type(array_list))

type of array list <class 'numpy.ndarray'>


In [10]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.|

In [11]:
print("Data type in list :")
for item in list_:
    print(f"Element : {item}, Data Type : {type(item)}")
    
print("\nData type in array list: ")
for item in array_list:
    print(f"Element : {item} , Data Type : {type(item)}")

Data type in list :
Element : 1, Data Type : <class 'str'>
Element : 2, Data Type : <class 'str'>
Element : 3, Data Type : <class 'str'>
Element : 4, Data Type : <class 'str'>
Element : 5, Data Type : <class 'str'>

Data type in array list: 
Element : 1 , Data Type : <class 'numpy.str_'>
Element : 2 , Data Type : <class 'numpy.str_'>
Element : 3 , Data Type : <class 'numpy.str_'>
Element : 4 , Data Type : <class 'numpy.str_'>
Element : 5 , Data Type : <class 'numpy.str_'>


In [12]:
#Q3. Considering the following changes in the variable, array_list:
#array_list = np.array(object = list_, dtype = int)
# there be any difference in the data type of the elements present in both the variables, list_ and arra_list?
#If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [13]:
array_list = np.array(object = list_, dtype = int)

print("Data type in list :")
for item in list_:
    print(f"Element : {item}, Data Type : {type(item)}")
    
print("\nData type in array list: ")
for item in array_list:
    print(f"Element : {item} , Data Type : {type(item)}")

Data type in list :
Element : 1, Data Type : <class 'str'>
Element : 2, Data Type : <class 'str'>
Element : 3, Data Type : <class 'str'>
Element : 4, Data Type : <class 'str'>
Element : 5, Data Type : <class 'str'>

Data type in array list: 
Element : 1 , Data Type : <class 'numpy.int64'>
Element : 2 , Data Type : <class 'numpy.int64'>
Element : 3 , Data Type : <class 'numpy.int64'>
Element : 4 , Data Type : <class 'numpy.int64'>
Element : 5 , Data Type : <class 'numpy.int64'>


We're asking NumPy to convert the string elements in list_ into integer values and create the NumPy array. If the conversion is possible, the resulting array will have the dtype int. If the conversion is not possible (for example, if the strings contain non-numeric characters), an error will occur.`

In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

In [17]:
print("The shape of array is : ", num_array.shape)

The shape of array is :  (2, 3)


In [18]:
print("The size of array is : ", num_array.size)

The size of array is :  6


In [19]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [21]:
import numpy as np
arr=np.zeros([3,3])

In [22]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr.size

9

In [24]:
arr.shape

(3, 3)

In [25]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [26]:
import numpy as np
arr=np.eye(5)

In [27]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])